"""La Liga 2026/27 configuration."""

from epl_predictor.leagues.base import LeagueConfig, make_context

CSV_NAME = {
    'Deportivo Alavés': 'Alaves',
    'Athletic Club': 'Ath Bilbao',
    'Atlético de Madrid': 'Ath Madrid',
    'Barcelona': 'Barcelona',
    'Real Betis': 'Betis',
    'Celta de Vigo': 'Celta',
    'Elche': 'Elche',
    'Espanyol': 'Espanol',
    'Getafe': 'Getafe',
    'Levante': 'Levante',
    'Osasuna': 'Osasuna',
    'Real Madrid': 'Real Madrid',
    'Sevilla': 'Sevilla',
    'Real Sociedad': 'Sociedad',
    'Valencia': 'Valencia',
    'Rayo Vallecano': 'Vallecano',
    'Villarreal': 'Villarreal',
    'Racing Santander': 'Santander',
    'Deportivo La Coruña': 'La Coruna',
    'Málaga': 'Malaga',
}

LAST_SEASON_POSITION = {
    'Barcelona': 1,
    'Real Madrid': 2,
    'Villarreal': 3,
    'Atlético de Madrid': 4,
    'Real Betis': 5,
    'Celta de Vigo': 6,
    'Getafe': 7,
    'Rayo Vallecano': 8,
    'Valencia': 9,
    'Real Sociedad': 10,
    'Espanyol': 11,
    'Athletic Club': 12,
    'Elche': 13,
    'Deportivo Alavés': 14,
    'Sevilla': 15,
    'Osasuna': 16,
    'Levante': 17,
    'Racing Santander': 21,
    'Deportivo La Coruña': 22,
    'Málaga': 23,
}

PROMOTED = frozenset(['Deportivo La Coruña', 'Málaga', 'Racing Santander'])

TEAM_CONTEXT = {
    'Deportivo Alavés': make_context('Eduardo Coudet', net_spend_m=8, squad_turnover=0.2, key_ins=['centre-back', 'holding midfielder'], key_outs=['first-choice winger'], notes='A settled defensive core should support another survival campaign.'),
    'Athletic Club': make_context('Ernesto Valverde', pedigree='elite', net_spend_m=18, squad_turnover=0.14, key_ins=['academy forward'], key_outs=['rotation defender'], notes='Academy continuity and strong home form keep the floor high.'),
    'Atlético de Madrid': make_context('Diego Simeone', pedigree='elite', net_spend_m=55, squad_turnover=0.22, key_ins=['starting striker', 'ball-playing defender'], key_outs=['veteran midfielder'], notes='Heavy investment reinforces an established title-level structure.'),
    'Barcelona': make_context('Hansi Flick', pedigree='elite', net_spend_m=65, squad_turnover=0.18, key_ins=['elite winger', 'full-back'], key_outs=['senior forward'], notes='The champions retain elite attacking quality with selective renewal.'),
    'Real Betis': make_context('Manuel Pellegrini', pedigree='elite', net_spend_m=22, squad_turnover=0.2, key_ins=['creative midfielder', 'striker'], key_outs=['wide forward'], notes='Experienced management and technical depth support European contention.'),
    'Celta de Vigo': make_context('Claudio Giráldez', net_spend_m=15, squad_turnover=0.17, key_ins=['mobile forward'], key_outs=['backup midfielder'], notes='Continuity in a progressive system should preserve upper-mid-table form.'),
    'Elche': make_context('Eder Sarabia', net_spend_m=10, squad_turnover=0.24, key_ins=['centre-forward', 'full-back'], key_outs=['loan midfielder'], notes='Targeted additions add depth after a stable first season back.'),
    'Espanyol': make_context('Manolo González', net_spend_m=9, squad_turnover=0.23, key_ins=['box-to-box midfielder'], key_outs=['starting defender'], notes='A pragmatic setup offsets moderate squad churn.'),
    'Getafe': make_context('José Bordalás', net_spend_m=7, squad_turnover=0.19, key_ins=['target forward'], key_outs=['central midfielder'], notes="A durable low-event style remains the club's main advantage."),
    'Levante': make_context('Julián Calero', net_spend_m=11, squad_turnover=0.25, key_ins=['goalkeeper', 'centre-back'], key_outs=['veteran forward'], notes='Defensive recruitment is aimed at consolidating top-flight status.'),
    'Osasuna': make_context('Alessio Lisci', net_spend_m=8, squad_turnover=0.18, key_ins=['wide attacker'], key_outs=['rotation full-back'], notes='A cohesive squad and strong home edge reduce relegation risk.'),
    'Real Madrid': make_context('Carlo Ancelotti', pedigree='elite', net_spend_m=80, squad_turnover=0.18, key_ins=['elite defender', 'central midfielder'], key_outs=['veteran playmaker'], notes='World-class depth keeps Madrid among the clear title favourites.'),
    'Sevilla': make_context('Matías Almeyda', net_spend_m=12, squad_turnover=0.3, key_ins=['starting centre-back', 'striker'], key_outs=['senior midfielder', 'winger'], notes='Continued restructuring raises variance despite improved athleticism.'),
    'Real Sociedad': make_context('Sergio Francisco', net_spend_m=20, squad_turnover=0.2, key_ins=['creative winger'], key_outs=['first-team midfielder'], notes='Academy quality and a strong defensive base support a rebound.'),
    'Valencia': make_context('Carlos Corberán', net_spend_m=18, squad_turnover=0.21, key_ins=['centre-forward', 'right-back'], key_outs=['young centre-back'], notes='A young squad gains depth while retaining a high-intensity identity.'),
    'Rayo Vallecano': make_context('Iñigo Pérez', net_spend_m=9, squad_turnover=0.22, key_ins=['pressing forward'], key_outs=['starting winger'], notes='Pressing intensity and continuity keep Rayo competitive.'),
    'Villarreal': make_context('Marcelino', net_spend_m=42, squad_turnover=0.2, key_ins=['top-level striker', 'centre-back'], key_outs=['wide attacker'], notes='Champions League resources strengthen an already productive attack.'),
    'Racing Santander': make_context('José Alberto López', change_type='summer', pedigree='unproven', promoted=True, net_spend_m=22, squad_turnover=0.3, key_ins=['top-flight centre-back', 'holding midfielder'], key_outs=['promotion winger'], notes='Promotion momentum is balanced by limited top-flight experience.'),
    'Deportivo La Coruña': make_context('Antonio Hidalgo', change_type='summer', pedigree='unproven', promoted=True, net_spend_m=25, squad_turnover=0.31, key_ins=['experienced striker', 'goalkeeper'], key_outs=['loan playmaker'], notes='A large refresh attempts to translate an attacking promotion side upward.'),
    'Málaga': make_context('Juanma Barrero', change_type='summer', pedigree='unproven', promoted=True, net_spend_m=20, squad_turnover=0.32, key_ins=['centre-back', 'box-to-box midfielder'], key_outs=['veteran captain'], notes='Squad depth is the primary concern after promotion.'),
}

NAME_ALIASES = {
    'Athletic Club': 'Ath Bilbao',
    'Atlético de Madrid': 'Ath Madrid',
    'Atletico de Madrid': 'Ath Madrid',
    'FC Barcelona': 'Barcelona',
    'Real Betis': 'Betis',
    'Celta': 'Celta',
    'Celta de Vigo': 'Celta',
    'Deportivo Alavés': 'Alaves',
    'Deportivo Alaves': 'Alaves',
    'Elche CF': 'Elche',
    'RCD Espanyol': 'Espanol',
    'Espanyol': 'Espanol',
    'Getafe CF': 'Getafe',
    'CA Osasuna': 'Osasuna',
    'Rayo Vallecano': 'Vallecano',
    'Real Sociedad': 'Sociedad',
    'Sevilla FC': 'Sevilla',
    'Valencia CF': 'Valencia',
    'Villarreal CF': 'Villarreal',
    'Racing Santander': 'Santander',
    'Racing de Santander': 'Santander',
    'Deportivo A Coruña': 'La Coruna',
    'Deportivo La Coruña': 'La Coruna',
    'Málaga CF': 'Malaga',
    'Malaga CF': 'Malaga',
    'Levante UD': 'Levante',
    'R. Racing Club': 'Santander',
    'RC Deportivo': 'La Coruna',
    'RCD Espanyol de Barcelona': 'Espanol',
}

CONFIG = LeagueConfig(
    id='laliga', name='La Liga', fd_code='SP1',
    index_url='https://www.football-data.co.uk/spainm.php', currency='€',
    second_tier_label='Segunda División', fixture_feed_slug='la-liga-2026',
    matchweek_count=38, csv_name=CSV_NAME,
    last_season_position=LAST_SEASON_POSITION, promoted=PROMOTED,
    team_context=TEAM_CONTEXT, name_aliases=NAME_ALIASES,
    season_start='2026-08-15', context_as_of='20 Aug 2026',
)
