"""Ligue 1 2026/27 configuration."""

from epl_predictor.leagues.base import LeagueConfig, make_context

CSV_NAME = {
    'Angers SCO': 'Angers',
    'AJ Auxerre': 'Auxerre',
    'Stade Brestois': 'Brest',
    'Le Havre': 'Le Havre',
    'RC Lens': 'Lens',
    'LOSC Lille': 'Lille',
    'FC Lorient': 'Lorient',
    'Olympique Lyonnais': 'Lyon',
    'Olympique de Marseille': 'Marseille',
    'AS Monaco': 'Monaco',
    'OGC Nice': 'Nice',
    'Paris FC': 'Paris FC',
    'Paris Saint-Germain': 'Paris SG',
    'Stade Rennais': 'Rennes',
    'RC Strasbourg Alsace': 'Strasbourg',
    'Toulouse': 'Toulouse',
    'ESTAC Troyes': 'Troyes',
    'Le Mans': 'Le Mans',
}

LAST_SEASON_POSITION = {
    'Paris Saint-Germain': 1,
    'RC Lens': 2,
    'LOSC Lille': 3,
    'Olympique Lyonnais': 4,
    'Olympique de Marseille': 5,
    'Stade Rennais': 6,
    'AS Monaco': 7,
    'RC Strasbourg Alsace': 8,
    'Toulouse': 9,
    'FC Lorient': 10,
    'Paris FC': 11,
    'Stade Brestois': 12,
    'Angers SCO': 13,
    'Le Havre': 14,
    'AJ Auxerre': 15,
    'OGC Nice': 16,
    'ESTAC Troyes': 21,
    'Le Mans': 22,
}

PROMOTED = frozenset(['ESTAC Troyes', 'Le Mans'])

TEAM_CONTEXT = {
    'Angers SCO': make_context('Stéphane Gilli', previous_manager='Alexandre Dujeux', change_type='summer', net_spend_m=8, squad_turnover=0.25, key_ins=['centre-forward', 'full-back'], key_outs=['starting midfielder'], notes='A coaching transition adds risk to an otherwise settled survival squad.'),
    'AJ Auxerre': make_context('Will Still', previous_manager='Christophe Pélissier', change_type='summer', net_spend_m=13, squad_turnover=0.25, key_ins=['pressing winger', 'centre-back'], key_outs=['veteran striker'], notes='A proactive new coach should lift intensity after a difficult season.'),
    'Stade Brestois': make_context('Julien Lachuer', previous_manager='Eric Roy', change_type='summer', net_spend_m=12, squad_turnover=0.27, key_ins=['creative midfielder'], key_outs=['first-choice defender'], notes='Managerial change tests a club accustomed to outperforming its budget.'),
    'Le Havre': make_context('Didier Digard', net_spend_m=7, squad_turnover=0.22, key_ins=['target forward'], key_outs=['starting full-back'], notes='Defensive organisation remains essential with limited resources.'),
    'RC Lens': make_context('Dino Toppmöller', previous_manager='Pierre Sage', change_type='summer', pedigree='elite', net_spend_m=35, squad_turnover=0.23, key_ins=['starting striker', 'central midfielder'], key_outs=['key defender'], notes='Strong recruitment and an experienced coach sustain Champions League ambitions.'),
    'LOSC Lille': make_context('Davide Ancelotti', previous_manager='Bruno Génésio', change_type='summer', net_spend_m=30, squad_turnover=0.24, key_ins=['centre-forward', 'ball-playing defender'], key_outs=['leading scorer'], notes='A talented squad must adapt quickly to a first-time head coach.'),
    'FC Lorient': make_context('Alexandre Dujeux', previous_manager='Olivier Pantaloni', change_type='summer', net_spend_m=14, squad_turnover=0.24, key_ins=['wide forward'], key_outs=['holding midfielder'], notes='A coaching reset targets safer mid-table consolidation.'),
    'Olympique Lyonnais': make_context('Paulo Fonseca', pedigree='elite', net_spend_m=38, squad_turnover=0.24, key_ins=['creative winger', 'centre-back'], key_outs=['senior striker'], notes='High-end attacking talent offsets financial constraints and turnover.'),
    'Olympique de Marseille': make_context('Bruno Genesio', previous_manager='Roberto De Zerbi', change_type='summer', pedigree='elite', net_spend_m=55, squad_turnover=0.28, key_ins=['elite forward', 'starting defender'], key_outs=['two senior attackers'], notes='Major investment gives a new coach immediate Champions League expectations.'),
    'AS Monaco': make_context('Filipe Luís', previous_manager='Sébastien Pocognoli', change_type='summer', net_spend_m=45, squad_turnover=0.27, key_ins=['fast striker', 'holding midfielder'], key_outs=['star playmaker'], notes='Elite youth remains abundant despite another summer of churn.'),
    'OGC Nice': make_context('Olivier Pantaloni', previous_manager='Franck Haise', change_type='summer', net_spend_m=18, squad_turnover=0.29, key_ins=['centre-back', 'goalkeeper'], key_outs=['leading winger'], notes='A broad reset follows an underperforming season.'),
    'Paris FC': make_context('Liam Rosenior', previous_manager='Stéphane Gilli', change_type='summer', net_spend_m=42, squad_turnover=0.27, key_ins=['top-flight striker', 'creative midfielder'], key_outs=['rotation defender'], notes='Ownership backing supports an ambitious second top-flight season.'),
    'Paris Saint-Germain': make_context('Luis Enrique', pedigree='elite', net_spend_m=75, key_ins=['elite midfielder', 'full-back'], key_outs=['rotation forward'], notes='Exceptional depth and tactical continuity make PSG overwhelming favourites.'),
    'Stade Rennais': make_context('Franck Haise', net_spend_m=32, squad_turnover=0.23, key_ins=['starting winger', 'centre-back'], key_outs=['young midfielder'], notes='A well-coached, balanced squad should remain in European contention.'),
    'RC Strasbourg Alsace': make_context('Hugo Oliveira', previous_manager='Liam Rosenior', change_type='summer', net_spend_m=50, squad_turnover=0.3, key_ins=['high-upside forward', 'central defender'], key_outs=['leading scorer'], notes='Deep investment is tempered by youth and managerial transition.'),
    'Toulouse': make_context('Jens Berthel Askou', previous_manager='Carles Martínez Novell', change_type='summer', net_spend_m=16, squad_turnover=0.24, key_ins=['striker', 'left-back'], key_outs=['creative midfielder'], notes='Smart recruitment should preserve a stable mid-table level.'),
    'ESTAC Troyes': make_context('Stéphane Dumont', change_type='summer', pedigree='unproven', promoted=True, net_spend_m=24, squad_turnover=0.31, key_ins=['Ligue 1 centre-back', 'holding midfielder'], key_outs=['loan winger'], notes='Multi-club resources strengthen a promoted squad with limited experience.'),
    'Le Mans': make_context('Patrick Videira', change_type='summer', pedigree='unproven', promoted=True, net_spend_m=16, squad_turnover=0.34, key_ins=['goalkeeper', 'target forward'], key_outs=['promotion playmaker'], notes="The promoted side faces the division's steepest depth challenge."),
}

NAME_ALIASES = {
    'Paris Saint-Germain': 'Paris SG',
    'PSG': 'Paris SG',
    'Olympique de Marseille': 'Marseille',
    'Marseille': 'Marseille',
    'Olympique Lyonnais': 'Lyon',
    'Lyon': 'Lyon',
    'RC Lens': 'Lens',
    'Lens': 'Lens',
    'LOSC Lille': 'Lille',
    'Lille': 'Lille',
    'AS Monaco': 'Monaco',
    'Monaco': 'Monaco',
    'Stade Rennais': 'Rennes',
    'Stade Rennais FC': 'Rennes',
    'Rennes': 'Rennes',
    'RC Strasbourg Alsace': 'Strasbourg',
    'Strasbourg': 'Strasbourg',
    'OGC Nice': 'Nice',
    'Nice': 'Nice',
    'AJ Auxerre': 'Auxerre',
    'Auxerre': 'Auxerre',
    'Angers SCO': 'Angers',
    'Angers': 'Angers',
    'FC Lorient': 'Lorient',
    'Lorient': 'Lorient',
    'Havre Athletic Club': 'Le Havre',
    'Le Havre': 'Le Havre',
    'Estac Troyes': 'Troyes',
    'ESTAC Troyes': 'Troyes',
    'Troyes': 'Troyes',
    'Le Mans FC': 'Le Mans',
    'Toulouse FC': 'Toulouse',
    'Paris FC': 'Paris FC',
    'Stade Brestois 29': 'Brest',
    'Brest': 'Brest',
}

CONFIG = LeagueConfig(
    id='ligue1', name='Ligue 1', fd_code='F1',
    index_url='https://www.football-data.co.uk/francem.php', currency='€',
    second_tier_label='Ligue 2', fixture_feed_slug='ligue-1-2026',
    matchweek_count=34, csv_name=CSV_NAME,
    last_season_position=LAST_SEASON_POSITION, promoted=PROMOTED,
    team_context=TEAM_CONTEXT, name_aliases=NAME_ALIASES,
    season_start='2026-08-21', context_as_of='20 Aug 2026',
)
