"""Primeira Liga 2026/27 configuration."""

from epl_predictor.leagues.base import LeagueConfig, make_context

CSV_NAME = {
    'FC Alverca': 'Alverca',
    'FC Arouca': 'Arouca',
    'Benfica': 'Benfica',
    'Casa Pia': 'Casa Pia',
    'Estoril Praia': 'Estoril',
    'Estrela da Amadora': 'Estrela',
    'FC Famalicão': 'Famalicao',
    'Gil Vicente': 'Gil Vicente',
    'Vitória Guimarães': 'Guimaraes',
    'Moreirense': 'Moreirense',
    'CD Nacional': 'Nacional',
    'FC Porto': 'Porto',
    'Rio Ave': 'Rio Ave',
    'Santa Clara': 'Santa Clara',
    'SC Braga': 'Sp Braga',
    'Sporting CP': 'Sp Lisbon',
    'Académico de Viseu': 'Academico',
    'Marítimo': 'Maritimo',
}

LAST_SEASON_POSITION = {
    'Sporting CP': 1,
    'Benfica': 2,
    'FC Porto': 3,
    'SC Braga': 4,
    'Vitória Guimarães': 5,
    'FC Famalicão': 6,
    'Santa Clara': 7,
    'Moreirense': 8,
    'Estoril Praia': 9,
    'Gil Vicente': 10,
    'Casa Pia': 11,
    'FC Arouca': 12,
    'Rio Ave': 13,
    'CD Nacional': 14,
    'Estrela da Amadora': 15,
    'FC Alverca': 16,
    'Académico de Viseu': 21,
    'Marítimo': 22,
}

PROMOTED = frozenset(['Académico de Viseu', 'Marítimo'])

TEAM_CONTEXT = {
    'FC Alverca': make_context('Custódio Castro', net_spend_m=9, squad_turnover=0.27, key_ins=['centre-back', 'holding midfielder'], key_outs=['starting winger'], notes='A second-year squad adds defensive depth after a narrow survival.'),
    'FC Arouca': make_context('Vasco Seabra', net_spend_m=10, squad_turnover=0.22, key_ins=['mobile forward'], key_outs=['first-choice full-back'], notes='Sound recruitment and continuity support a mid-table baseline.'),
    'Benfica': make_context('Bruno Lage', pedigree='elite', net_spend_m=68, squad_turnover=0.23, key_ins=['elite winger', 'central midfielder'], key_outs=['star defender'], notes='Deep investment keeps Benfica among the clear title favourites.'),
    'Casa Pia': make_context('João Pereira', net_spend_m=7, squad_turnover=0.24, key_ins=['target striker'], key_outs=['starting midfielder'], notes='Compact organisation remains the foundation of a modest squad.'),
    'Estoril Praia': make_context('Ian Cathro', net_spend_m=13, squad_turnover=0.25, key_ins=['young winger', 'centre-back'], key_outs=['leading scorer'], notes='An effective development model offsets recurring player sales.'),
    'Estrela da Amadora': make_context('José Faria', net_spend_m=8, squad_turnover=0.28, key_ins=['goalkeeper', 'centre-forward'], key_outs=['senior defender'], notes='High turnover makes another survival fight likely.'),
    'FC Famalicão': make_context('Hugo Oliveira', net_spend_m=16, squad_turnover=0.22, key_ins=['creative midfielder', 'full-back'], key_outs=['young centre-back'], notes='A talented young core can challenge for the European places.'),
    'Gil Vicente': make_context('César Peixoto', net_spend_m=11, squad_turnover=0.21, key_ins=['wide forward'], key_outs=['rotation midfielder'], notes='Tactical continuity and balanced depth support top-half ambitions.'),
    'Vitória Guimarães': make_context('Luís Freire', net_spend_m=20, squad_turnover=0.2, key_ins=['starting striker', 'centre-back'], key_outs=['creative winger'], notes='Strong home form and European experience sustain a high floor.'),
    'Moreirense': make_context('Vasco Botelho da Costa', net_spend_m=9, squad_turnover=0.19, key_ins=['central midfielder'], key_outs=['rotation striker'], notes='A stable, efficient squad should remain safely mid-table.'),
    'CD Nacional': make_context('Tiago Margarido', net_spend_m=8, squad_turnover=0.23, key_ins=['centre-back', 'winger'], key_outs=['starting forward'], notes='Island home advantage remains important to the survival outlook.'),
    'FC Porto': make_context('Vítor Bruno', pedigree='elite', net_spend_m=58, squad_turnover=0.24, key_ins=['elite striker', 'ball-playing defender'], key_outs=['senior midfielder'], notes='Substantial reinforcement gives Porto a credible title challenge.'),
    'Rio Ave': make_context('Petit', net_spend_m=9, squad_turnover=0.23, key_ins=['holding midfielder'], key_outs=['starting full-back'], notes='Experienced coaching and a physical spine should secure safety.'),
    'Santa Clara': make_context('Vasco Matos', net_spend_m=12, squad_turnover=0.18, key_ins=['wide attacker'], key_outs=['backup defender'], notes='Excellent continuity supports another upper-mid-table finish.'),
    'SC Braga': make_context('Carlos Carvalhal', net_spend_m=35, squad_turnover=0.22, key_ins=['goal-scoring winger', 'centre-back'], key_outs=['starting striker'], notes='Europa-level depth keeps Braga firmly inside the leading four.'),
    'Sporting CP': make_context('Rui Borges', pedigree='elite', net_spend_m=62, squad_turnover=0.2, key_ins=['elite forward', 'wing-back'], key_outs=['leading scorer'], notes='The champions retain system continuity and outstanding domestic depth.'),
    'Académico de Viseu': make_context('Sérgio Vieira', change_type='summer', pedigree='unproven', promoted=True, net_spend_m=15, squad_turnover=0.32, key_ins=['Primeira Liga defender', 'striker'], key_outs=['promotion midfielder'], notes='A first top-flight campaign brings substantial depth and experience concerns.'),
    'Marítimo': make_context('Ivo Vieira', change_type='summer', pedigree='unproven', promoted=True, net_spend_m=18, squad_turnover=0.3, key_ins=['experienced goalkeeper', 'centre-back'], key_outs=['loan winger'], notes="Top-flight history and home advantage improve the promoted club's prospects."),
}

NAME_ALIASES = {
    'SL Benfica': 'Benfica',
    'Benfica': 'Benfica',
    'FC Porto': 'Porto',
    'Porto': 'Porto',
    'Sporting CP': 'Sp Lisbon',
    'Sporting Lisbon': 'Sp Lisbon',
    'Sporting Lisboa': 'Sp Lisbon',
    'SC Braga': 'Sp Braga',
    'Braga': 'Sp Braga',
    'Vitória SC': 'Guimaraes',
    'Vitoria SC': 'Guimaraes',
    'Vitória Guimarães': 'Guimaraes',
    'FC Famalicão': 'Famalicao',
    'FC Famalicao': 'Famalicao',
    'CD Nacional': 'Nacional',
    'Nacional': 'Nacional',
    'Casa Pia AC': 'Casa Pia',
    'GD Estoril Praia': 'Estoril',
    'Estoril': 'Estoril',
    'Estrela Amadora': 'Estrela',
    'CF Estrela da Amadora': 'Estrela',
    'FC Alverca': 'Alverca',
    'FC Arouca': 'Arouca',
    'Gil Vicente FC': 'Gil Vicente',
    'Moreirense FC': 'Moreirense',
    'Rio Ave FC': 'Rio Ave',
    'CD Santa Clara': 'Santa Clara',
    'Académico': 'Academico',
    'Academico': 'Academico',
    'Académico de Viseu': 'Academico',
    'CS Marítimo': 'Maritimo',
    'Marítimo': 'Maritimo',
    'Maritimo': 'Maritimo',
    'Marítimo M.': 'Maritimo',
    'Maritimo M.': 'Maritimo',
}

CONFIG = LeagueConfig(
    id='portugal', name='Primeira Liga', fd_code='P1',
    index_url='https://www.football-data.co.uk/portugalm.php', currency='€',
    second_tier_label='Liga Portugal 2', fixture_feed_slug='primeira-liga-2026',
    matchweek_count=34, csv_name=CSV_NAME,
    last_season_position=LAST_SEASON_POSITION, promoted=PROMOTED,
    team_context=TEAM_CONTEXT, name_aliases=NAME_ALIASES,
    season_start='2026-08-10', context_as_of='20 Aug 2026',
)
