"""Serie A 2026/27 configuration."""

from epl_predictor.leagues.base import LeagueConfig, make_context

CSV_NAME = {
    'Atalanta': 'Atalanta',
    'Bologna': 'Bologna',
    'Cagliari': 'Cagliari',
    'Como': 'Como',
    'Fiorentina': 'Fiorentina',
    'Genoa': 'Genoa',
    'Inter': 'Inter',
    'Juventus': 'Juventus',
    'Lazio': 'Lazio',
    'Lecce': 'Lecce',
    'AC Milan': 'Milan',
    'Napoli': 'Napoli',
    'Parma': 'Parma',
    'Roma': 'Roma',
    'Sassuolo': 'Sassuolo',
    'Torino': 'Torino',
    'Udinese': 'Udinese',
    'Venezia': 'Venezia',
    'Frosinone': 'Frosinone',
    'Monza': 'Monza',
}

LAST_SEASON_POSITION = {
    'Inter': 1,
    'Napoli': 2,
    'Roma': 3,
    'Como': 4,
    'AC Milan': 5,
    'Juventus': 6,
    'Atalanta': 7,
    'Bologna': 8,
    'Lazio': 9,
    'Udinese': 10,
    'Sassuolo': 11,
    'Parma': 12,
    'Torino': 13,
    'Cagliari': 14,
    'Fiorentina': 15,
    'Genoa': 16,
    'Lecce': 17,
    'Venezia': 21,
    'Frosinone': 22,
    'Monza': 23,
}

PROMOTED = frozenset(['Frosinone', 'Monza', 'Venezia'])

TEAM_CONTEXT = {
    'Atalanta': make_context('Maurizio Sarri', previous_manager='Ivan Jurić', change_type='summer', pedigree='elite', net_spend_m=38, squad_turnover=0.25, key_ins=['technical midfielder', 'centre-forward'], key_outs=['starting wing-back'], notes='A proven coach inherits a deep squad but introduces a major style change.'),
    'Bologna': make_context('Domenico Tedesco', previous_manager='Vincenzo Italiano', change_type='summer', net_spend_m=28, squad_turnover=0.24, key_ins=['pressing forward', 'centre-back'], key_outs=['creative winger'], notes='European-quality depth should soften the managerial transition.'),
    'Cagliari': make_context('Fabio Pisacane', net_spend_m=10, squad_turnover=0.22, key_ins=['target striker'], key_outs=['starting midfielder'], notes='Continuity and home form remain central to survival.'),
    'Como': make_context('Cesc Fàbregas', net_spend_m=70, squad_turnover=0.23, key_ins=['elite playmaker', 'ball-playing defender'], key_outs=['rotation forward'], notes='Exceptional backing and tactical continuity support another top-four push.'),
    'Fiorentina': make_context('Fabio Grosso', previous_manager='Stefano Pioli', change_type='summer', net_spend_m=25, squad_turnover=0.28, key_ins=['centre-forward', 'holding midfielder'], key_outs=['senior winger'], notes="A coaching reset seeks to reverse last season's sharp decline."),
    'Genoa': make_context('Daniele De Rossi', net_spend_m=13, squad_turnover=0.22, key_ins=['central defender', 'winger'], key_outs=['leading striker'], notes='A compact structure offsets limited attacking resources.'),
    'Inter': make_context('Cristian Chivu', pedigree='elite', net_spend_m=58, squad_turnover=0.19, key_ins=['young striker', 'central midfielder'], key_outs=['veteran defender'], notes="The champions retain the division's deepest and most balanced squad."),
    'Juventus': make_context('Luciano Spalletti', pedigree='elite', net_spend_m=62, squad_turnover=0.24, key_ins=['elite striker', 'full-back'], key_outs=['starting forward'], notes='Heavy investment and an elite coach raise the title ceiling.'),
    'Lazio': make_context('Gennaro Gattuso', previous_manager='Maurizio Sarri', change_type='summer', net_spend_m=24, squad_turnover=0.27, key_ins=['box-to-box midfielder', 'winger'], key_outs=['senior playmaker'], notes='A more direct approach follows significant technical turnover.'),
    'Lecce': make_context('Eusebio Di Francesco', net_spend_m=8, squad_turnover=0.25, key_ins=['centre-forward', 'full-back'], key_outs=['starting centre-back'], notes='Survival again depends on extracting value from a young squad.'),
    'AC Milan': make_context('Rúben Amorim', previous_manager='Massimiliano Allegri', change_type='summer', pedigree='elite', net_spend_m=72, squad_turnover=0.29, key_ins=['elite forward', 'wing-back'], key_outs=['senior midfielder', 'centre-back'], notes='A major tactical rebuild has high upside and high early variance.'),
    'Napoli': make_context('Massimiliano Allegri', previous_manager='Antonio Conte', change_type='summer', pedigree='elite', net_spend_m=64, squad_turnover=0.23, key_ins=['starting striker', 'central defender'], key_outs=['star winger'], notes='A proven winner and strong depth keep Napoli in the title race.'),
    'Parma': make_context('Carlos Cuesta', net_spend_m=19, squad_turnover=0.2, key_ins=['creative midfielder'], key_outs=['rotation striker'], notes='A young side should improve with another year in the same structure.'),
    'Roma': make_context('Gian Piero Gasperini', pedigree='elite', net_spend_m=50, squad_turnover=0.22, key_ins=['mobile forward', 'wing-back'], key_outs=['veteran attacker'], notes='Tactical continuity and tailored recruitment support a title challenge.'),
    'Sassuolo': make_context('Alberto Aquilani', previous_manager='Fabio Grosso', change_type='summer', net_spend_m=18, squad_turnover=0.25, key_ins=['holding midfielder', 'centre-back'], key_outs=['leading winger'], notes='A new coach inherits enough technical quality for mid-table safety.'),
    'Torino': make_context('Ignazio Abate', previous_manager='Marco Baroni', change_type='summer', net_spend_m=15, squad_turnover=0.26, key_ins=['striker', 'right-back'], key_outs=['starting defender'], notes='A younger coach and moderate churn make the early outlook uncertain.'),
    'Udinese': make_context('Kosta Runjaić', net_spend_m=16, squad_turnover=0.2, key_ins=['forward', 'central midfielder'], key_outs=['first-choice wing-back'], notes='Physical quality and continuity point to another secure mid-table finish.'),
    'Venezia': make_context('Giovanni Stroppa', change_type='summer', pedigree='unproven', promoted=True, net_spend_m=25, squad_turnover=0.31, key_ins=['Serie A defender', 'goalkeeper'], key_outs=['loan striker'], notes='Possession quality is promising but top-flight depth remains limited.'),
    'Frosinone': make_context('Massimiliano Alvini', change_type='summer', pedigree='unproven', promoted=True, net_spend_m=20, squad_turnover=0.33, key_ins=['centre-back', 'holding midfielder'], key_outs=['promotion winger'], notes='A hard-running promoted group faces a large defensive step up.'),
    'Monza': make_context('Ivan Jurić', change_type='summer', pedigree='unproven', promoted=True, net_spend_m=34, squad_turnover=0.3, key_ins=['experienced striker', 'ball-playing defender'], key_outs=['young playmaker'], notes='Investment and an intense coach give Monza the strongest promoted profile.'),
}

NAME_ALIASES = {
    'Internazionale': 'Inter',
    'Inter Milan': 'Inter',
    'FC Internazionale': 'Inter',
    'AC Milan': 'Milan',
    'SSC Napoli': 'Napoli',
    'Napoli': 'Napoli',
    'AS Roma': 'Roma',
    'Roma': 'Roma',
    'Juventus FC': 'Juventus',
    'SS Lazio': 'Lazio',
    'Atalanta BC': 'Atalanta',
    'Bologna FC': 'Bologna',
    'Cagliari Calcio': 'Cagliari',
    'Como 1907': 'Como',
    'ACF Fiorentina': 'Fiorentina',
    'Genoa CFC': 'Genoa',
    'US Lecce': 'Lecce',
    'Parma Calcio 1913': 'Parma',
    'US Sassuolo': 'Sassuolo',
    'Torino FC': 'Torino',
    'Udinese Calcio': 'Udinese',
    'Venezia FC': 'Venezia',
    'Frosinone Calcio': 'Frosinone',
    'AC Monza': 'Monza',
}

CONFIG = LeagueConfig(
    id='seriea', name='Serie A', fd_code='I1',
    index_url='https://www.football-data.co.uk/italym.php', currency='€',
    second_tier_label='Serie B', fixture_feed_slug='serie-a-2026',
    matchweek_count=38, csv_name=CSV_NAME,
    last_season_position=LAST_SEASON_POSITION, promoted=PROMOTED,
    team_context=TEAM_CONTEXT, name_aliases=NAME_ALIASES,
    season_start='2026-08-22', context_as_of='20 Aug 2026',
)
