"""Süper Lig 2026/27 configuration."""

from epl_predictor.leagues.base import LeagueConfig, make_context

CSV_NAME = {
    'Alanyaspor': 'Alanyaspor',
    'Beşiktaş': 'Besiktas',
    'İstanbul Başakşehir': 'Buyuksehyr',
    'Eyüpspor': 'Eyupspor',
    'Fenerbahçe': 'Fenerbahce',
    'Galatasaray': 'Galatasaray',
    'Gaziantep FK': 'Gaziantep',
    'Gençlerbirliği': 'Genclerbirligi',
    'Göztepe': 'Goztep',
    'Kasımpaşa': 'Kasimpasa',
    'Kocaelispor': 'Kocaelispor',
    'Konyaspor': 'Konyaspor',
    'Çaykur Rizespor': 'Rizespor',
    'Samsunspor': 'Samsunspor',
    'Trabzonspor': 'Trabzonspor',
    'Amedspor': 'Amedspor',
    'Erzurumspor': 'Erzurumspor',
    'Çorum': 'Corum',
}

LAST_SEASON_POSITION = {
    'Galatasaray': 1,
    'Fenerbahçe': 2,
    'Trabzonspor': 3,
    'Beşiktaş': 4,
    'İstanbul Başakşehir': 5,
    'Samsunspor': 6,
    'Göztepe': 7,
    'Çaykur Rizespor': 8,
    'Konyaspor': 9,
    'Gaziantep FK': 10,
    'Alanyaspor': 11,
    'Kocaelispor': 12,
    'Eyüpspor': 13,
    'Kasımpaşa': 14,
    'Gençlerbirliği': 15,
    'Amedspor': 21,
    'Erzurumspor': 22,
    'Çorum': 23,
}

PROMOTED = frozenset(['Amedspor', 'Erzurumspor', 'Çorum'])

TEAM_CONTEXT = {
    'Alanyaspor': make_context('João Pereira', net_spend_m=9, squad_turnover=0.24, key_ins=['mobile striker', 'full-back'], key_outs=['starting winger'], notes='Smart foreign recruitment supports a stable mid-table outlook.'),
    'Beşiktaş': make_context('Sergen Yalçın', pedigree='elite', net_spend_m=48, squad_turnover=0.27, key_ins=['elite winger', 'central defender'], key_outs=['veteran midfielder'], notes='Major investment should narrow the gap to the leading pair.'),
    'İstanbul Başakşehir': make_context('Çağdaş Atan', net_spend_m=22, squad_turnover=0.21, key_ins=['creative midfielder', 'striker'], key_outs=['starting full-back'], notes='Experienced depth keeps Başakşehir in European contention.'),
    'Eyüpspor': make_context('Selçuk Şahin', net_spend_m=14, squad_turnover=0.27, key_ins=['holding midfielder'], key_outs=['leading attacker'], notes='A technical squad must replace important attacking output.'),
    'Fenerbahçe': make_context('José Mourinho', pedigree='elite', net_spend_m=72, squad_turnover=0.23, key_ins=['elite striker', 'centre-back'], key_outs=['senior forward'], notes='Elite spending and management maintain strong title expectations.'),
    'Galatasaray': make_context('Okan Buruk', pedigree='elite', net_spend_m=80, squad_turnover=0.19, key_ins=['elite playmaker', 'full-back'], key_outs=['rotation winger'], notes="The champions retain the league's strongest squad and attacking depth."),
    'Gaziantep FK': make_context('Burak Yılmaz', net_spend_m=11, squad_turnover=0.25, key_ins=['centre-forward', 'central midfielder'], key_outs=['starting defender'], notes='Home strength and added attacking pace point to mid-table safety.'),
    'Gençlerbirliği': make_context('Hüseyin Eroğlu', net_spend_m=10, squad_turnover=0.29, key_ins=['experienced centre-back', 'winger'], key_outs=['promotion-era striker'], notes='A refreshed squad remains vulnerable after a difficult first season.'),
    'Göztepe': make_context('Stanimir Stoilov', net_spend_m=24, squad_turnover=0.2, key_ins=['goal-scoring forward', 'wing-back'], key_outs=['central defender'], notes='Strong coaching and ownership backing support European ambitions.'),
    'Kasımpaşa': make_context('Shota Arveladze', net_spend_m=8, squad_turnover=0.29, key_ins=['striker', 'goalkeeper'], key_outs=['creative midfielder'], notes='Recurring turnover creates a wide range of outcomes.'),
    'Kocaelispor': make_context('Selçuk İnan', net_spend_m=16, squad_turnover=0.24, key_ins=['centre-back', 'box-to-box midfielder'], key_outs=['starting winger'], notes='Support, physicality and selective upgrades provide a survival cushion.'),
    'Konyaspor': make_context('Recep Uçar', net_spend_m=12, squad_turnover=0.22, key_ins=['target forward'], key_outs=['veteran midfielder'], notes='A settled defensive structure supports a safe mid-table projection.'),
    'Çaykur Rizespor': make_context('İlhan Palut', net_spend_m=14, squad_turnover=0.2, key_ins=['wide attacker', 'full-back'], key_outs=['rotation striker'], notes='Continuity and strong home performances sustain a top-half challenge.'),
    'Samsunspor': make_context('Thomas Reis', net_spend_m=27, squad_turnover=0.22, key_ins=['creative winger', 'centre-back'], key_outs=['leading midfielder'], notes='European-level organisation should survive the loss of one key player.'),
    'Trabzonspor': make_context('Abdullah Avcı', pedigree='elite', net_spend_m=42, squad_turnover=0.24, key_ins=['starting striker', 'holding midfielder'], key_outs=['senior defender'], notes='A proven coach and strong home edge support another top-four finish.'),
    'Amedspor': make_context('Servet Çetin', change_type='summer', pedigree='unproven', promoted=True, net_spend_m=22, squad_turnover=0.33, key_ins=['Süper Lig centre-back', 'goalkeeper'], key_outs=['promotion winger'], notes='Aggressive recruitment helps offset a first season at this level.'),
    'Erzurumspor': make_context('Hakan Kutlu', change_type='summer', pedigree='unproven', promoted=True, net_spend_m=17, squad_turnover=0.31, key_ins=['target striker', 'holding midfielder'], key_outs=['loan defender'], notes='Altitude and home form are key advantages for a shallow promoted squad.'),
    'Çorum': make_context('İsmet Taşdemir', change_type='summer', pedigree='unproven', promoted=True, net_spend_m=15, squad_turnover=0.32, key_ins=['Süper Lig centre-back', 'goalkeeper'], key_outs=['promotion winger'], notes='Play-off winners face a steep defensive step-up in the top flight.'),
}

NAME_ALIASES = {
    'Beşiktaş': 'Besiktas',
    'Besiktas JK': 'Besiktas',
    'İstanbul Başakşehir': 'Buyuksehyr',
    'Istanbul Basaksehir': 'Buyuksehyr',
    'Başakşehir': 'Buyuksehyr',
    'Eyüpspor': 'Eyupspor',
    'Eyupspor': 'Eyupspor',
    'Fenerbahçe': 'Fenerbahce',
    'Fenerbahce': 'Fenerbahce',
    'Galatasaray SK': 'Galatasaray',
    'Gaziantep FK': 'Gaziantep',
    'Gençlerbirliği': 'Genclerbirligi',
    'Genclerbirligi': 'Genclerbirligi',
    'Gençlerbirligi': 'Genclerbirligi',
    'Göztepe': 'Goztep',
    'Goztepe': 'Goztep',
    'Kasımpaşa': 'Kasimpasa',
    'Kasimpasa': 'Kasimpasa',
    'Çaykur Rizespor': 'Rizespor',
    'Caykur Rizespor': 'Rizespor',
    'Trabzonspor AŞ': 'Trabzonspor',
    'Amed SK': 'Amedspor',
    'Amedspor': 'Amedspor',
    'Erzurumspor FK': 'Erzurumspor',
    'BB Erzurumspor': 'Erzurumspor',
    'Çorum': 'Corum',
    'Corum': 'Corum',
    'Çorum FK': 'Corum',
}

CONFIG = LeagueConfig(
    id='turkey', name='Süper Lig', fd_code='T1',
    index_url='https://www.football-data.co.uk/turkeym.php', currency='€',
    second_tier_label='TFF 1. Lig', fixture_feed_slug='super-lig-2026',
    matchweek_count=34, csv_name=CSV_NAME,
    last_season_position=LAST_SEASON_POSITION, promoted=PROMOTED,
    team_context=TEAM_CONTEXT, name_aliases=NAME_ALIASES,
    season_start='2026-08-14', context_as_of='20 Aug 2026',
)
